seed: 1
device: null
visualize: false # visualize results using trimesh
verbose: false
extrinsics_path: ./camera/workspace/calibration.json
data1: ./example_data/img/20231010_monkey_original # reference
data2: ./example_data/img/20231010_monkey_test # test
hand_ref_pose_name: monkey
model_path: ./example_data/pth/glayer_key0_monkey_64_T0.007_20000.pth
img_preprocess: 
  - sam
  - sam
scale: 14
dis_threshold: 0.1
quotient_threshold: 0.8
method: vote_3D # prune method
mode: hand
hand_model:
  tip_aug: 4
  pt_nums: 500
alignment:
  opt_iterations: 300